### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by dexhunter**
Signed-off-by: Dixing (Dex) Xu <dixingxu@gmail.com>

### CODE REVIEW

**Comment by joelparkerhenderson** [comment]
Thanks! Could you amend this PR so it does the description typo fixes, and doesn't change the route? (The route is correct)

**Comment by dexhunter** [comment]
ok, but the `curl` at README uses `demo-json`, should I change that instead?

**Comment by dexhunter** [comment]
> Ahh, yes, you're right and yes please change that curl. Thanks for reading so carefully, I appreciate you.

No problem, I've changed accordingly please have a look.

**Comment by joelparkerhenderson** [comment]
Perfect, thank you.

**Pull request merged**
